# preload your wallpapers (optional, but improves performance)
preload = /home/cisztah/Pictures/wallpaper7.jpg

# assign to specific monitors
wallpaper {
    monitor = DP-1
    path = /home/cisztah/Pictures/wallpaper7.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/cisztah/Pictures/wallpaper7.jpg
    fit_mode = cover
}

# fallback for any monitor without specific wallpaper
wallpaper {
    monitor =
    path = /home/cisztah/Pictures/wallpaper7.jpg
    fit_mode = cover
}

# misc (optional)
ipc = true
splash = false